### ISSUE TITLE
Preloading middleware's error_handler triggers "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by sorccu** [halt-hammerzeit/react-isomorphic-render#24] opened 2016-10-18 07:32 UTC
Seems like preloading_middleware takes an `error_handler` argument [here](https://github.com/halt-hammerzeit/react-isomorphic-render/blob/cdfb45a9539a6f88257285a1b74e81214b9a62ab/source/redux/middleware/preloading%20middleware.js#L172). However, it is soon shadowed by a local variable [here](https://github.com/halt-hammerzeit/react-isomorphic-render/blob/cdfb45a9539a6f88257285a1b74e81214b9a62ab/source/redux/middleware/preloading%20middleware.js#L193). Then, inside the new `error_handler`, it attempts to call the argument `error_handler`, and obviously things don't go very well from there. One of them should be renamed.

**Comment by halt-hammerzeit** [comment] 2016-10-18 07:44
Oh shoot, didn't check that one after the whole renaming-and-refactoring thing.
Seems to be fixed in the new version, check it out.
I'm currently helping with construction and renovation so may be unavailable till the evening, and I also have no time to check if it works (but it should) because they're calling me to do the work.

**Closed** 2016-10-18 07:43 UTC

**Comment by sorccu** [comment] 2016-10-18 07:46
No worries it's open source! You do what you want when you want. I'll try and let you know if it works.

**Comment by sorccu** [comment] 2016-10-18 08:01
It does work but now I don't get the fancy styled error page, it's just plain text. I'm not sure where exactly things go wrong though yet.

**Comment by halt-hammerzeit** [comment] 2016-10-18 08:18
> It does work but now I don't get the fancy styled error page, it's just plain text.

Can you give me more details?
Maybe a screenshot?
Because for my project it's now working as intended.
